debugStoreFile=twg_keystore.jks
debugKeyAlias=twg
debugStorePassword=123456aA@
debugKeyPassword=123456aA@

releaseStoreFile=twg_keystore.jks
releaseKeyAlias=twg
releaseStorePassword=123456aA@
releaseKeyPassword=123456aA@