package nz.co.warehouseandroidtest.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

val lightColorScheme = ColorScheme(
    primary = Color(0xFFCC0000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD4),
    onPrimaryContainer = Color(0xFF410000),
    inversePrimary = Color(0xFFFFB4A8),
    secondary = Color(0xFF80534B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD4),
    onSecondaryContainer = Color(0xFF32120D),
    tertiary = Color(0xFF3E5CA3),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDAE2FF),
    onTertiaryContainer = Color(0xFF001847),
    background = Color(0xFFFFF8F6),
    onBackground = Color(0xFF201A19),
    surface = Color(0xFFFFF8F6),
    onSurface = Color(0xFF201A19),
    surfaceVariant = Color(0xFFFFFBFA),
    onSurfaceVariant = Color(0xFF534341),
    surfaceTint = Color(0xFF201A19),
    inverseSurface = Color(0xFF362F2E),
    inverseOnSurface = Color(0xFFFBEEEC),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF857370),
    outlineVariant = Color(0xFFD8C2BE),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F6),
    surfaceDim = Color(0xFFE4D7D5),
    surfaceContainer = Color(0xFFF8EBE9),
    surfaceContainerHigh = Color(0xFFF3E5E3),
    surfaceContainerHighest = Color(0xFFEDE0DD),
    surfaceContainerLow = Color(0xFFFEF1EE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

val darkColorScheme = ColorScheme(
    primary = Color(0xFFFF8A78),
    onPrimary = Color(0xFF550000),
    primaryContainer = Color(0xFF930000),
    onPrimaryContainer = Color(0xFFFFDAD4),
    inversePrimary = Color(0xFFCC0000),
    secondary = Color(0xFFF4B8AF),
    onSecondary = Color(0xFF4B2620),
    secondaryContainer = Color(0xFF653C35),
    onSecondaryContainer = Color(0xFFFFDAD4),
    tertiary = Color(0xFFB1C5FF),
    onTertiary = Color(0xFF002C72),
    tertiaryContainer = Color(0xFF234389),
    onTertiaryContainer = Color(0xFFDAE2FF),
    background = Color(0xFF2B2423),
    onBackground = Color(0xFFEDE0DD),
    surface = Color(0xFF2B2423),
    onSurface = Color(0xFFEDE0DD),
    surfaceVariant = Color(0xFF3F3736),
    onSurfaceVariant = Color(0xFFD8C2BE),
    surfaceTint = Color(0xFFEDE0DD),
    inverseSurface = Color(0xFFEDE0DD),
    inverseOnSurface = Color(0xFF362F2E),
    error = Color(0xFFDE3730),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFFA08C89),
    outlineVariant = Color(0xFF534341),
    scrim = Color(0xFF201A19),
    surfaceBright = Color(0xFF3F3736),
    surfaceDim = Color(0xFF181211),
    surfaceContainer = Color(0xFF251E1D),
    surfaceContainerHigh = Color(0xFF2F2827),
    surfaceContainerHighest = Color(0xFF3B3332),
    surfaceContainerLow = Color(0xFF201A19),
    surfaceContainerLowest = Color(0xFF120D0C),
)
